name: fluttershop
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^1.1.0
  url_launcher: ^5.4.10
  flutter_easyrefresh: ^1.2.7
  provide: 1.0.2
  fluttertoast: ^4.0.0
  fluro: "^1.6.3"
  flutter_html: ^1.0.0-pre.1
  shared_preferences: ^0.5.1
#  jpush_flutter:
#    git:
#      url: git://github.com/jpush/jpush-flutter-plugin.git
#      ref: master
  jpush_flutter: 0.5.5
  webview_flutter: ^0.3.22+1
  fluwx:
    git: https://github.com/OpenFlutter/fluwx.git
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - lang/en.json
    - lang/zh.json
    - images/1129218.png
    - images/1134354.png

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
